### ISSUE TITLE
Inference on strings in C++ not working

### ISSUE THREAD

**Issue by LorenzoMattia** [leimao/ONNX-Runtime-Inference#17]
Hi @leimao , sorry to bother you. I am trying to do something similar to what you did here and after a long search on the web I came across your repo.

I built a model composed by a Sklearn Pipeline of a CountVectorizer and an SVM model with the aim of classifying some variable length strings and I exported it in ONNX format. While using this model in python with the onnxruntime library works perfectly, in C++ it always returns the exact same result. Inspecting the process I discovered that the problem is probably located in the CountVectorizer, which always returns a matrix of zeros.

Have you faced a similar problem about inference on strings or do you know how this could be solved?

Hoping for an answer from you, have a good day!

**Comment by leimao** [comment]
No. You should pay more attention to your preprocessing and postprocessing. The ONNX model and the ONNX library themselves should be fine. I cannot help you debug because it's always in the details.
For general deep learning inference debug guideline, please check my article ["How To Debug Deep Learning Inference Applications"](https://leimao.github.io/article/How-To-Debug-Deep-Learning-Inference-Applications/).
